[package]
name = "example"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.julia-sys]
path = "../julia-sys"
